//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKimlikNoileAdresSorguKriteri", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TCKimlikNoileAdresSorguKriteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiAdresBilgileriSonucu", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiAdresBilgileriSonucu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgileri> SorguSonucuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgileri> SorguSonucu {
            get {
                return this.SorguSonucuField;
            }
            set {
                if ((object.ReferenceEquals(this.SorguSonucuField, value) != true)) {
                    this.SorguSonucuField = value;
                    this.RaisePropertyChanged("SorguSonucu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class Parametre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod {
            get {
                return this.KodField;
            }
            set {
                if ((this.KodField.Equals(value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiAdresBilgileri", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiAdresBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgisi> DigerAdresBilgileriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgisi YerlesimYeriAdresiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgisi> DigerAdresBilgileri {
            get {
                return this.DigerAdresBilgileriField;
            }
            set {
                if ((object.ReferenceEquals(this.DigerAdresBilgileriField, value) != true)) {
                    this.DigerAdresBilgileriField = value;
                    this.RaisePropertyChanged("DigerAdresBilgileri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgisi YerlesimYeriAdresi {
            get {
                return this.YerlesimYeriAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.YerlesimYeriAdresiField, value) != true)) {
                    this.YerlesimYeriAdresiField = value;
                    this.RaisePropertyChanged("YerlesimYeriAdresi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiAdresBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiAdresBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcikAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AdresNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre AdresTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.BeldeAdresi BeldeAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi BeyanTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.IlIlceMerkezi IlIlceMerkezAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KoyAdresi KoyAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi TasinmaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi TescilTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.YurtDisiAdresi YurtDisiAdresiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcikAdres {
            get {
                return this.AcikAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AcikAdresField, value) != true)) {
                    this.AcikAdresField = value;
                    this.RaisePropertyChanged("AcikAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AdresNo {
            get {
                return this.AdresNoField;
            }
            set {
                if ((this.AdresNoField.Equals(value) != true)) {
                    this.AdresNoField = value;
                    this.RaisePropertyChanged("AdresNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre AdresTip {
            get {
                return this.AdresTipField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresTipField, value) != true)) {
                    this.AdresTipField = value;
                    this.RaisePropertyChanged("AdresTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.BeldeAdresi BeldeAdresi {
            get {
                return this.BeldeAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.BeldeAdresiField, value) != true)) {
                    this.BeldeAdresiField = value;
                    this.RaisePropertyChanged("BeldeAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi BeyanTarihi {
            get {
                return this.BeyanTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.BeyanTarihiField, value) != true)) {
                    this.BeyanTarihiField = value;
                    this.RaisePropertyChanged("BeyanTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.IlIlceMerkezi IlIlceMerkezAdresi {
            get {
                return this.IlIlceMerkezAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.IlIlceMerkezAdresiField, value) != true)) {
                    this.IlIlceMerkezAdresiField = value;
                    this.RaisePropertyChanged("IlIlceMerkezAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KoyAdresi KoyAdresi {
            get {
                return this.KoyAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyAdresiField, value) != true)) {
                    this.KoyAdresiField = value;
                    this.RaisePropertyChanged("KoyAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi TasinmaTarihi {
            get {
                return this.TasinmaTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.TasinmaTarihiField, value) != true)) {
                    this.TasinmaTarihiField = value;
                    this.RaisePropertyChanged("TasinmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TarihBilgisi TescilTarihi {
            get {
                return this.TescilTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.TescilTarihiField, value) != true)) {
                    this.TescilTarihiField = value;
                    this.RaisePropertyChanged("TescilTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.YurtDisiAdresi YurtDisiAdresi {
            get {
                return this.YurtDisiAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.YurtDisiAdresiField, value) != true)) {
                    this.YurtDisiAdresiField = value;
                    this.RaisePropertyChanged("YurtDisiAdresi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldeAdresi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class BeldeAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BucakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BucakKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bucak {
            get {
                return this.BucakField;
            }
            set {
                if ((object.ReferenceEquals(this.BucakField, value) != true)) {
                    this.BucakField = value;
                    this.RaisePropertyChanged("Bucak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BucakKod {
            get {
                return this.BucakKodField;
            }
            set {
                if ((this.BucakKodField.Equals(value) != true)) {
                    this.BucakKodField = value;
                    this.RaisePropertyChanged("BucakKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((this.DisKapiNoField.Equals(value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy {
            get {
                return this.KoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyField, value) != true)) {
                    this.KoyField = value;
                    this.RaisePropertyChanged("Koy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo {
            get {
                return this.KoyKayitNoField;
            }
            set {
                if ((this.KoyKayitNoField.Equals(value) != true)) {
                    this.KoyKayitNoField = value;
                    this.RaisePropertyChanged("KoyKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKod {
            get {
                return this.KoyKodField;
            }
            set {
                if ((this.KoyKodField.Equals(value) != true)) {
                    this.KoyKodField = value;
                    this.RaisePropertyChanged("KoyKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKod {
            get {
                return this.MahalleKodField;
            }
            set {
                if ((this.MahalleKodField.Equals(value) != true)) {
                    this.MahalleKodField = value;
                    this.RaisePropertyChanged("MahalleKod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay {
            get {
                return this.AyField;
            }
            set {
                if ((this.AyField.Equals(value) != true)) {
                    this.AyField = value;
                    this.RaisePropertyChanged("Ay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun {
            get {
                return this.GunField;
            }
            set {
                if ((this.GunField.Equals(value) != true)) {
                    this.GunField = value;
                    this.RaisePropertyChanged("Gun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil {
            get {
                return this.YilField;
            }
            set {
                if ((this.YilField.Equals(value) != true)) {
                    this.YilField = value;
                    this.RaisePropertyChanged("Yil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlIlceMerkezi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class IlIlceMerkezi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((this.DisKapiNoField.Equals(value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKod {
            get {
                return this.MahalleKodField;
            }
            set {
                if ((this.MahalleKodField.Equals(value) != true)) {
                    this.MahalleKodField = value;
                    this.RaisePropertyChanged("MahalleKod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KoyAdresi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KoyAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BucakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BucakKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsbmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CsbmKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DisKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcKapiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKayitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KoyKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MahalleKodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bucak {
            get {
                return this.BucakField;
            }
            set {
                if ((object.ReferenceEquals(this.BucakField, value) != true)) {
                    this.BucakField = value;
                    this.RaisePropertyChanged("Bucak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BucakKod {
            get {
                return this.BucakKodField;
            }
            set {
                if ((this.BucakKodField.Equals(value) != true)) {
                    this.BucakKodField = value;
                    this.RaisePropertyChanged("BucakKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm {
            get {
                return this.CsbmField;
            }
            set {
                if ((object.ReferenceEquals(this.CsbmField, value) != true)) {
                    this.CsbmField = value;
                    this.RaisePropertyChanged("Csbm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu {
            get {
                return this.CsbmKoduField;
            }
            set {
                if ((this.CsbmKoduField.Equals(value) != true)) {
                    this.CsbmKoduField = value;
                    this.RaisePropertyChanged("CsbmKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DisKapiNo {
            get {
                return this.DisKapiNoField;
            }
            set {
                if ((this.DisKapiNoField.Equals(value) != true)) {
                    this.DisKapiNoField = value;
                    this.RaisePropertyChanged("DisKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo {
            get {
                return this.IcKapiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcKapiNoField, value) != true)) {
                    this.IcKapiNoField = value;
                    this.RaisePropertyChanged("IcKapiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu {
            get {
                return this.IlKoduField;
            }
            set {
                if ((this.IlKoduField.Equals(value) != true)) {
                    this.IlKoduField = value;
                    this.RaisePropertyChanged("IlKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu {
            get {
                return this.IlceKoduField;
            }
            set {
                if ((this.IlceKoduField.Equals(value) != true)) {
                    this.IlceKoduField = value;
                    this.RaisePropertyChanged("IlceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy {
            get {
                return this.KoyField;
            }
            set {
                if ((object.ReferenceEquals(this.KoyField, value) != true)) {
                    this.KoyField = value;
                    this.RaisePropertyChanged("Koy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo {
            get {
                return this.KoyKayitNoField;
            }
            set {
                if ((this.KoyKayitNoField.Equals(value) != true)) {
                    this.KoyKayitNoField = value;
                    this.RaisePropertyChanged("KoyKayitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKod {
            get {
                return this.KoyKodField;
            }
            set {
                if ((this.KoyKodField.Equals(value) != true)) {
                    this.KoyKodField = value;
                    this.RaisePropertyChanged("KoyKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle {
            get {
                return this.MahalleField;
            }
            set {
                if ((object.ReferenceEquals(this.MahalleField, value) != true)) {
                    this.MahalleField = value;
                    this.RaisePropertyChanged("Mahalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKod {
            get {
                return this.MahalleKodField;
            }
            set {
                if ((this.MahalleKodField.Equals(value) != true)) {
                    this.MahalleKodField = value;
                    this.RaisePropertyChanged("MahalleKod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YurtDisiAdresi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class YurtDisiAdresi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YabanciAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YabanciSehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre YabanciUlkeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciAdres {
            get {
                return this.YabanciAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciAdresField, value) != true)) {
                    this.YabanciAdresField = value;
                    this.RaisePropertyChanged("YabanciAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciSehir {
            get {
                return this.YabanciSehirField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciSehirField, value) != true)) {
                    this.YabanciSehirField = value;
                    this.RaisePropertyChanged("YabanciSehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.Parametre YabanciUlke {
            get {
                return this.YabanciUlkeField;
            }
            set {
                if ((object.ReferenceEquals(this.YabanciUlkeField, value) != true)) {
                    this.YabanciUlkeField = value;
                    this.RaisePropertyChanged("YabanciUlke");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContracts.BaseFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsBusinessFaultContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsValidationFaultContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsSecurityFaultContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsTechnicalFaultContract))]
    public partial class FaultContractsBaseFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContracts.BusinessFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
    [System.SerializableAttribute()]
    public partial class FaultContractsBusinessFaultContract : Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsBaseFaultContract {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContracts.ValidationFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
    [System.SerializableAttribute()]
    public partial class FaultContractsValidationFaultContract : Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsBaseFaultContract {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContracts.SecurityFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
    [System.SerializableAttribute()]
    public partial class FaultContractsSecurityFaultContract : Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsBaseFaultContract {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContracts.TechnicalFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
    [System.SerializableAttribute()]
    public partial class FaultContractsTechnicalFaultContract : Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsBaseFaultContract {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2011/01/01", ConfigurationName="TCKimlikAdresSorgula.TcKimlikNoSorgulaAdresServis")]
    public interface TcKimlikNoSorgulaAdresServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2011/01/01/TcKimlikNoSorgulaAdresServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2011/01/01/TcKimlikNoSorgulaAdresServis/SorgulaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.FaultContractsTechnicalFaultContract), Action="http://framework/faults", Name="FaultContracts.TechnicalFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Framework.Communications.Wcf.FaultTypes")]
        Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgileriSonucu Sorgula(System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TCKimlikNoileAdresSorguKriteri> kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TcKimlikNoSorgulaAdresServisChannel : Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TcKimlikNoSorgulaAdresServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TcKimlikNoSorgulaAdresServisClient : System.ServiceModel.ClientBase<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TcKimlikNoSorgulaAdresServis>, Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TcKimlikNoSorgulaAdresServis {
        
        public TcKimlikNoSorgulaAdresServisClient() {
        }
        
        public TcKimlikNoSorgulaAdresServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TcKimlikNoSorgulaAdresServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TcKimlikNoSorgulaAdresServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TcKimlikNoSorgulaAdresServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.KisiAdresBilgileriSonucu Sorgula(System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.TCKimlikAdresSorgula.TCKimlikNoileAdresSorguKriteri> kriterListesi) {
            return base.Channel.Sorgula(kriterListesi);
        }
    }
}
