//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mernis.Kps.Sample.Net.WCF.KisiListele {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiListeleSorguKriteri", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiListeleSorguKriteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BaslangicTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BitisTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Mernis.Kps.Sample.Net.WCF.KisiListele.CstCinsiyet> CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SayfaAnahtariField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BaslangicTarih {
            get {
                return this.BaslangicTarihField;
            }
            set {
                if ((this.BaslangicTarihField.Equals(value) != true)) {
                    this.BaslangicTarihField = value;
                    this.RaisePropertyChanged("BaslangicTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BitisTarih {
            get {
                return this.BitisTarihField;
            }
            set {
                if ((this.BitisTarihField.Equals(value) != true)) {
                    this.BitisTarihField = value;
                    this.RaisePropertyChanged("BitisTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Mernis.Kps.Sample.Net.WCF.KisiListele.CstCinsiyet> Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((this.CinsiyetField.Equals(value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((this.IlceField.Equals(value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SayfaAnahtari {
            get {
                return this.SayfaAnahtariField;
            }
            set {
                if ((this.SayfaAnahtariField.Equals(value) != true)) {
                    this.SayfaAnahtariField = value;
                    this.RaisePropertyChanged("SayfaAnahtari");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CstCinsiyet", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public enum CstCinsiyet : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bilinmeyen = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erkek = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kadin = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiListesiSonucu", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiListesiSonucu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListesi SorguSonucuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListesi SorguSonucu {
            get {
                return this.SorguSonucuField;
            }
            set {
                if ((object.ReferenceEquals(this.SorguSonucuField, value) != true)) {
                    this.SorguSonucuField = value;
                    this.RaisePropertyChanged("SorguSonucu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class Parametre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod {
            get {
                return this.KodField;
            }
            set {
                if ((this.KodField.Equals(value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiListesi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiListesi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SayfaAnahtariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.DogumTarihveCinsiyeteGoreKisiBilgisi[] SonucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SayfaAnahtari {
            get {
                return this.SayfaAnahtariField;
            }
            set {
                if ((this.SayfaAnahtariField.Equals(value) != true)) {
                    this.SayfaAnahtariField = value;
                    this.RaisePropertyChanged("SayfaAnahtari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.DogumTarihveCinsiyeteGoreKisiBilgisi[] Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DogumTarihveCinsiyeteGoreKisiBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class DogumTarihveCinsiyeteGoreKisiBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AnneTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BabaTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.KisiDurumBilgisi DurumBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EsTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.KisiKayitYeriBilgisi KayitYeriBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.KisiTemelBilgisi TemelBilgisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneTCKimlikNo {
            get {
                return this.AnneTCKimlikNoField;
            }
            set {
                if ((this.AnneTCKimlikNoField.Equals(value) != true)) {
                    this.AnneTCKimlikNoField = value;
                    this.RaisePropertyChanged("AnneTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaTCKimlikNo {
            get {
                return this.BabaTCKimlikNoField;
            }
            set {
                if ((this.BabaTCKimlikNoField.Equals(value) != true)) {
                    this.BabaTCKimlikNoField = value;
                    this.RaisePropertyChanged("BabaTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.KisiDurumBilgisi DurumBilgisi {
            get {
                return this.DurumBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumBilgisiField, value) != true)) {
                    this.DurumBilgisiField = value;
                    this.RaisePropertyChanged("DurumBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsTCKimlikNo {
            get {
                return this.EsTCKimlikNoField;
            }
            set {
                if ((this.EsTCKimlikNoField.Equals(value) != true)) {
                    this.EsTCKimlikNoField = value;
                    this.RaisePropertyChanged("EsTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.KisiKayitYeriBilgisi KayitYeriBilgisi {
            get {
                return this.KayitYeriBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitYeriBilgisiField, value) != true)) {
                    this.KayitYeriBilgisiField = value;
                    this.RaisePropertyChanged("KayitYeriBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.KisiTemelBilgisi TemelBilgisi {
            get {
                return this.TemelBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.TemelBilgisiField, value) != true)) {
                    this.TemelBilgisiField = value;
                    this.RaisePropertyChanged("TemelBilgisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiDurumBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre DinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre MedeniHalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.TarihBilgisi OlumTarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Din {
            get {
                return this.DinField;
            }
            set {
                if ((object.ReferenceEquals(this.DinField, value) != true)) {
                    this.DinField = value;
                    this.RaisePropertyChanged("Din");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre MedeniHal {
            get {
                return this.MedeniHalField;
            }
            set {
                if ((object.ReferenceEquals(this.MedeniHalField, value) != true)) {
                    this.MedeniHalField = value;
                    this.RaisePropertyChanged("MedeniHal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.TarihBilgisi OlumTarih {
            get {
                return this.OlumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.OlumTarihField, value) != true)) {
                    this.OlumTarihField = value;
                    this.RaisePropertyChanged("OlumTarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiKayitYeriBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiKayitYeriBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AileSiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BireySiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre CiltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre IlceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AileSiraNo {
            get {
                return this.AileSiraNoField;
            }
            set {
                if ((this.AileSiraNoField.Equals(value) != true)) {
                    this.AileSiraNoField = value;
                    this.RaisePropertyChanged("AileSiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BireySiraNo {
            get {
                return this.BireySiraNoField;
            }
            set {
                if ((this.BireySiraNoField.Equals(value) != true)) {
                    this.BireySiraNoField = value;
                    this.RaisePropertyChanged("BireySiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Cilt {
            get {
                return this.CiltField;
            }
            set {
                if ((object.ReferenceEquals(this.CiltField, value) != true)) {
                    this.CiltField = value;
                    this.RaisePropertyChanged("Cilt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiTemelBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BabaAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KisiListele.TarihBilgisi DogumTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumYerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd {
            get {
                return this.AnneAdField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneAdField, value) != true)) {
                    this.AnneAdField = value;
                    this.RaisePropertyChanged("AnneAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd {
            get {
                return this.BabaAdField;
            }
            set {
                if ((object.ReferenceEquals(this.BabaAdField, value) != true)) {
                    this.BabaAdField = value;
                    this.RaisePropertyChanged("BabaAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.Parametre Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KisiListele.TarihBilgisi DogumTarih {
            get {
                return this.DogumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumTarihField, value) != true)) {
                    this.DogumTarihField = value;
                    this.RaisePropertyChanged("DogumTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer {
            get {
                return this.DogumYerField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumYerField, value) != true)) {
                    this.DogumYerField = value;
                    this.RaisePropertyChanged("DogumYer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay {
            get {
                return this.AyField;
            }
            set {
                if ((this.AyField.Equals(value) != true)) {
                    this.AyField = value;
                    this.RaisePropertyChanged("Ay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun {
            get {
                return this.GunField;
            }
            set {
                if ((this.GunField.Equals(value) != true)) {
                    this.GunField = value;
                    this.RaisePropertyChanged("Gun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil {
            get {
                return this.YilField;
            }
            set {
                if ((this.YilField.Equals(value) != true)) {
                    this.YilField = value;
                    this.RaisePropertyChanged("Yil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2011/01/01", ConfigurationName="KisiListele.KisiListeleServis")]
    public interface KisiListeleServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2011/01/01/KisiListeleServis/Sayfala", ReplyAction="http://kps.nvi.gov.tr/2011/01/01/KisiListeleServis/SayfalaResponse")]
        Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListesiSonucu Sayfala(Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListeleSorguKriteri kriter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KisiListeleServisChannel : Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListeleServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KisiListeleServisClient : System.ServiceModel.ClientBase<Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListeleServis>, Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListeleServis {
        
        public KisiListeleServisClient() {
        }
        
        public KisiListeleServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KisiListeleServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisiListeleServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisiListeleServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListesiSonucu Sayfala(Mernis.Kps.Sample.Net.WCF.KisiListele.KisiListeleSorguKriteri kriter) {
            return base.Channel.Sayfala(kriter);
        }
    }
}
