//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mernis.Kps.Sample.Net.WCF.KPSKimlik {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiSorgulaTCKimlikNoSorguKriteri", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiSorgulaTCKimlikNoSorguKriteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiBilgisiSonucu", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiBilgisiSonucu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiBilgisi> SorguSonucuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiBilgisi> SorguSonucu {
            get {
                return this.SorguSonucuField;
            }
            set {
                if ((object.ReferenceEquals(this.SorguSonucuField, value) != true)) {
                    this.SorguSonucuField = value;
                    this.RaisePropertyChanged("SorguSonucu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class Parametre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod {
            get {
                return this.KodField;
            }
            set {
                if ((this.KodField.Equals(value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AnneTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BabaTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DogumYerKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiDurumBilgisi DurumBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EsTCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre HataBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiKayitYeriBilgisi KayitYeriBilgisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiTemelBilgisi TemelBilgisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneTCKimlikNo {
            get {
                return this.AnneTCKimlikNoField;
            }
            set {
                if ((this.AnneTCKimlikNoField.Equals(value) != true)) {
                    this.AnneTCKimlikNoField = value;
                    this.RaisePropertyChanged("AnneTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaTCKimlikNo {
            get {
                return this.BabaTCKimlikNoField;
            }
            set {
                if ((this.BabaTCKimlikNoField.Equals(value) != true)) {
                    this.BabaTCKimlikNoField = value;
                    this.RaisePropertyChanged("BabaTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYerKod {
            get {
                return this.DogumYerKodField;
            }
            set {
                if ((this.DogumYerKodField.Equals(value) != true)) {
                    this.DogumYerKodField = value;
                    this.RaisePropertyChanged("DogumYerKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiDurumBilgisi DurumBilgisi {
            get {
                return this.DurumBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumBilgisiField, value) != true)) {
                    this.DurumBilgisiField = value;
                    this.RaisePropertyChanged("DurumBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsTCKimlikNo {
            get {
                return this.EsTCKimlikNoField;
            }
            set {
                if ((this.EsTCKimlikNoField.Equals(value) != true)) {
                    this.EsTCKimlikNoField = value;
                    this.RaisePropertyChanged("EsTCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre HataBilgisi {
            get {
                return this.HataBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataBilgisiField, value) != true)) {
                    this.HataBilgisiField = value;
                    this.RaisePropertyChanged("HataBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiKayitYeriBilgisi KayitYeriBilgisi {
            get {
                return this.KayitYeriBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitYeriBilgisiField, value) != true)) {
                    this.KayitYeriBilgisiField = value;
                    this.RaisePropertyChanged("KayitYeriBilgisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((this.TCKimlikNoField.Equals(value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiTemelBilgisi TemelBilgisi {
            get {
                return this.TemelBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.TemelBilgisiField, value) != true)) {
                    this.TemelBilgisiField = value;
                    this.RaisePropertyChanged("TemelBilgisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiDurumBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre DinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre MedeniHalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.TarihBilgisi OlumTarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Din {
            get {
                return this.DinField;
            }
            set {
                if ((object.ReferenceEquals(this.DinField, value) != true)) {
                    this.DinField = value;
                    this.RaisePropertyChanged("Din");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre MedeniHal {
            get {
                return this.MedeniHalField;
            }
            set {
                if ((object.ReferenceEquals(this.MedeniHalField, value) != true)) {
                    this.MedeniHalField = value;
                    this.RaisePropertyChanged("MedeniHal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.TarihBilgisi OlumTarih {
            get {
                return this.OlumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.OlumTarihField, value) != true)) {
                    this.OlumTarihField = value;
                    this.RaisePropertyChanged("OlumTarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiKayitYeriBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiKayitYeriBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AileSiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BireySiraNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre CiltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre IlceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AileSiraNo {
            get {
                return this.AileSiraNoField;
            }
            set {
                if ((this.AileSiraNoField.Equals(value) != true)) {
                    this.AileSiraNoField = value;
                    this.RaisePropertyChanged("AileSiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BireySiraNo {
            get {
                return this.BireySiraNoField;
            }
            set {
                if ((this.BireySiraNoField.Equals(value) != true)) {
                    this.BireySiraNoField = value;
                    this.RaisePropertyChanged("BireySiraNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Cilt {
            get {
                return this.CiltField;
            }
            set {
                if ((object.ReferenceEquals(this.CiltField, value) != true)) {
                    this.CiltField = value;
                    this.RaisePropertyChanged("Cilt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class KisiTemelBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BabaAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mernis.Kps.Sample.Net.WCF.KPSKimlik.TarihBilgisi DogumTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumYerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd {
            get {
                return this.AnneAdField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneAdField, value) != true)) {
                    this.AnneAdField = value;
                    this.RaisePropertyChanged("AnneAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd {
            get {
                return this.BabaAdField;
            }
            set {
                if ((object.ReferenceEquals(this.BabaAdField, value) != true)) {
                    this.BabaAdField = value;
                    this.RaisePropertyChanged("BabaAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.Parametre Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.TarihBilgisi DogumTarih {
            get {
                return this.DogumTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumTarihField, value) != true)) {
                    this.DogumTarihField = value;
                    this.RaisePropertyChanged("DogumTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer {
            get {
                return this.DogumYerField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumYerField, value) != true)) {
                    this.DogumYerField = value;
                    this.RaisePropertyChanged("DogumYer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    [System.SerializableAttribute()]
    public partial class TarihBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay {
            get {
                return this.AyField;
            }
            set {
                if ((this.AyField.Equals(value) != true)) {
                    this.AyField = value;
                    this.RaisePropertyChanged("Ay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun {
            get {
                return this.GunField;
            }
            set {
                if ((this.GunField.Equals(value) != true)) {
                    this.GunField = value;
                    this.RaisePropertyChanged("Gun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil {
            get {
                return this.YilField;
            }
            set {
                if ((this.YilField.Equals(value) != true)) {
                    this.YilField = value;
                    this.RaisePropertyChanged("Yil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2011/01/01", ConfigurationName="KPSKimlik.KisiSorgulaTCKimlikNoServis")]
    public interface KisiSorgulaTCKimlikNoServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2011/01/01/KisiSorgulaTCKimlikNoServis/ListeleCoklu", ReplyAction="http://kps.nvi.gov.tr/2011/01/01/KisiSorgulaTCKimlikNoServis/ListeleCokluResponse" +
            "")]
        Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiBilgisiSonucu ListeleCoklu(System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiSorgulaTCKimlikNoSorguKriteri> kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KisiSorgulaTCKimlikNoServisChannel : Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiSorgulaTCKimlikNoServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KisiSorgulaTCKimlikNoServisClient : System.ServiceModel.ClientBase<Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiSorgulaTCKimlikNoServis>, Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiSorgulaTCKimlikNoServis {
        
        public KisiSorgulaTCKimlikNoServisClient() {
        }
        
        public KisiSorgulaTCKimlikNoServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KisiSorgulaTCKimlikNoServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisiSorgulaTCKimlikNoServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KisiSorgulaTCKimlikNoServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiBilgisiSonucu ListeleCoklu(System.Collections.Generic.List<Mernis.Kps.Sample.Net.WCF.KPSKimlik.KisiSorgulaTCKimlikNoSorguKriteri> kriterListesi) {
            return base.Channel.ListeleCoklu(kriterListesi);
        }
    }
}
